import React from 'react';
import Head from 'next/head';
import HomePage from '@components/PageComponent/HomePage';

export default function Home(props: any) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="canonical" href={props?.hostName} />
            </Head>
            <HomePage />
        </>
    );
}

export async function getServerSideProps({ req }: any) {
    return {
        props: {
            hostName: req.headers.host,
        },
    };
}
