#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

yarn lint ||
(
    echo '🆘🚫 Es Lint founded Error. Plesase recheck and commit again';
    false;
)
yarn lint-staged ||
(
    echo '🆘🚫 Prettier Format Failed. Run npm run lint-staged ==> and try commit again.';
    false;
)

echo '✅🐶 Successfully!! Already to commit!!'