#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run lint &&
npm run lint-staged ||
(
    echo '😴 Prettier Format Failed. Run npm run lint-staged ==> and try commit again.';
    false;
)

echo '✅🐶 Successfully!! I am ready to commit!!'